import FlashSale from '@/components/flashSale'
import HotSale from '@/components/flashSale/hotSale'
import Sliders from '@/components/sliders'
export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}
function Home() {
  return (
    <div className="Home page">
      {/* <Slider></Slider> */}
      <Sliders />
      <FlashSale />
      <HotSale />
    </div>
  )
}

export default Home
