'use client'
import Slider from '@/components/slider'
export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}
function Home() {
  return (
    <div className="Home page">
      {/* <Link href={'/login'}>đăng nhập</Link>
      <CustomButton text="Đăng nhập" /> */}
      <Slider></Slider>
    </div>
  )
}

export default Home
